Removed powertop from cpu-profile

diff --git a/cpu-profile b/cpu-profile
--- a/cpu-profile
+++ b/cpu-profile
@@ -48,9 +48,7 @@ Usage $SCRIPT_NAME [options] <arguments>
 	-g	Governor: choose your CPU governor. Posible
 		values are: conservative, performance, 
 		schedutil or ondemand.
-	-p	Powertop: if do you want to auto tune your
-		settings with powertop, you can choose:
-		full or nousb (to avoid usb autosuspend).
+	-p	Powertop: tune runtimes
 	-y	Yes: do not prompt for confirmation.
 	-h	Help: print this message.
 
@@ -102,20 +100,45 @@ choose_cores()
 # args: mode
 enable_powertop()
 {
-	sudo powertop --auto-tune > /dev/null || error "Error in autotune"
-	[ "$1" = "full" ] && return 0
-	for i in /sys/bus/usb/devices/*
-	do
-		target="/sys/bus/usb/devices/$i/power/control"
-		[ -f "$target" ] && [ -w "$target" ] && { printf "on\\n"	\
-			| sudo tee "$target" > /dev/null 			\
-			|| error "E in 'on' for $target"; }
-	done
-	return 0
+	echo '1500' | sudo tee '/proc/sys/vm/dirty_writeback_centisecs'
+	echo '1'    | sudo tee '/sys/module/snd_hda_intel/parameters/power_save'
+	echo 'auto' | sudo tee '/sys/bus/i2c/devices/i2c-5/device/power/control'
+	echo 'auto' | sudo tee '/sys/bus/i2c/devices/i2c-1/device/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:03:00.2/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:18.5/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:05:00.5/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:00.2/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:03:00.0/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:05:00.3/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:18.3/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:18.4/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:01.2/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:18.1/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:02:00.0/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:03:00.3/power/control' 
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:14.3/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:04:00.0/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:03:00.4/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:18.0/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:18.2/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:01.0/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:08.0/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:05:00.2/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:05:00.4/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:00.0/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:03:00.1/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:18.6/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:05:00.6/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:18.7/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:05:00.1/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:01.7/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:08.1/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:01.3/power/control'
+	echo 'auto' | sudo tee '/sys/bus/pci/devices/0000:00:01.4/power/control'
 }
 
 
-while getopts "hyf:c:g:p:" opt; do
+while getopts "hyf:c:g:p" opt; do
 	case $opt in
 		h)
 			usage
@@ -151,16 +174,8 @@ while getopts "hyf:c:g:p:" opt; do
 			CRS="$OPTARG"
 			;;
 		p)
-			command -v powertop > /dev/null 			\
-				|| error "You need powertop."
-			
 			[ -n "$PWRTOP" ] && error "Too many powertop opt"
-
-			{  [ "$OPTARG" = "nousb" ]				\
-			|| [ "$OPTARG" = "full" ];				\
-			} && PWRTOP="$OPTARG"
-
-			[ -z "$PWRTOP" ] && error "$OPTARG not accepted."
+			PWRTOP="true"
 			;;
 		*)
 			usage
@@ -202,6 +217,4 @@ for i in $( seq 1 "$CRS" ); do
 	sudo cpufreqctl --on --core="$i" || error "Error turning on core $i"
 done
 
-[ -n "$PWRTOP" ] && { printf "Entering powertop\\n"; 				\
-       	enable_powertop "$PWRTOP" > /dev/null 2>&1 				\
-	|| error "Error in powertop"; } 
+[ -n "$PWRTOP" ] && { enable_powertop > /dev/null || error "Error in runtimes"; }
