Improved gitio code quality

diff --git a/sh/gitio b/sh/gitio
--- a/sh/gitio
+++ b/sh/gitio
@@ -16,34 +16,25 @@ usage() {
 	EOF
 }
 
-[ $# -lt 1 ] && error "You need 1 input (Github) url"
+while [ "$#" -ne 0 ]; do case $1 in
+  -c)
+    [ -n "$code" ] && error "code already defined"
+    shift
+    code="$1"
+    shift
+    ;;
+  *)
+    [ -n "$url" ] && error "Url already defined"
+    url="$1"
+    shift
+    ;;
+esac done
 
-while [ "$#" -ne 0 ]; do
-	case $1 in
-		-c)
-			[ -n "$code" ] && error "code already defined"
-			shift
-			code="$1"
-			[ "$#" -eq 0 ] || shift
-			;;
-		*)
-			[ -n "$url" ] && error "Url already defined"
-			url="$1"
-			[ "$#" -eq 0 ] || shift
-			;;
-	esac
-done
+args="url=$url"
+[ -n "$code" ] && args="$args&code=$code"
 
-[ -z "$code" ] && \
-	out=$( curl -is https://git.io -F "url=$url" \
-		| grep "Location:" \
-		| cut -d' ' -f2 \
-		|| error "No internet connection" )
-[ -n "$code" ] && \
-	out=$( curl -is https://git.io -F "url=$url" -F "code=$code" \
-		| grep "Location:" \
-		| cut -d' ' -f2 \
-		|| error "No internet connection" )
-
-[ -z "$out" ] && error "Invalid Github url or invalid code"
-printf "%s\\n" "$out" 
+curl -is https://git.io -d "$args" || error "No internet connection" \
+  | grep "Location:" || error "Unprocessable Entity" \
+  | cut -d' ' -f2 \
+  | xargs -I '{}' printf "{}\\n" \
+  || error "No internet connection or Invalid URL"
